### ISSUE TITLE
Updating FAQs

### ISSUE THREAD

**Issue by AnaisUrlichs** [near/devx#103]
Updating the Community FAQs, Developer FAQs, and the Validator FAQs in the docs

**Comment by amgando** [comment]
@AnaisUrlichs can this be closed?

also, why is this in the Chain&Middleware pipeline?  seems like pure DevX / Docs related.

**Comment by AnaisUrlichs** [comment]
Yes, this is done [https://github.com/nearprotocol/docs/pull/282](https://github.com/nearprotocol/docs/pull/282)
