### ISSUE TITLE
Opening a specific example by a direct link starts with displaying 404 error

### ISSUE THREAD

**Issue by frol** [near/devx#105]
When I go to an example page via a direct link, I see Page not found 404 for a brief second: https://examples.nearprotocol.com/rust-status-message

**Comment by mikedotexe** [comment]
Oh dear. I wonder if this has something to do with the routing that @vgrichina was mentioning to @chadoh about. I think this might be a better tag for Chad, actually.

**Comment by chadoh** [comment]
Just pushed a fix: https://github.com/nearprotocol/render-ops/commit/fb87c711234477b534366fb55f149e0b409460fc

This had to do with how our [rewrites](https://render.com/docs/redirects-rewrites) were configured on Render.
