### ISSUE TITLE
Automation runs in CI

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#111]
- [x] Docs get built every time you push to near-api-js
- [x] Copy docs from near-api-js to docs repo
- [x] Redeploys docs repo

**Comment by janedegtiareva** [comment]
for ease of use: near-api-js is a rename from nearlib.

**Comment by chadoh** [comment]
Working on pulling most recent `near-api-js` docs into main docs repo here: https://github.com/nearprotocol/docs/pull/291

**Comment by potatodepaulo** [comment]
Links to the built docs are in the docs page.
