### ISSUE TITLE
Add comments to the public methods near-sdk-as

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#112]

**Comment by amgando** [comment]
almost done.  shipping as is and we can improve later

![image](https://user-images.githubusercontent.com/24913/78639167-264a3580-78b6-11ea-8a88-ccae4746de6d.png)

https://docs.google.com/spreadsheets/d/1kCzE__4JZhohHApGtRjZEIUM5pg-u1Zp775dYBX-mMQ/edit#gid=0

**Comment by amgando** [comment]
related PRs
- https://github.com/near/near-sdk-as/pull/26
- https://github.com/near/near-sdk-as/pull/30

**Comment by potatodepaulo** [comment]
Will be extended with https://github.com/near/devx/issues/111 @chadoh
