### ISSUE TITLE
Move dev accounts to .near/

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#116]
As a user, I expect my session to last outside of a repo.

**Comment by janedegtiareva** [comment]
This seems to not agree with the shell NEP https://github.com/nearprotocol/NEPs/blob/5bc61e292faf711d275fc7955a950015f8f8811c/text/0000-near-shell.md#3-key-management 

looks like we need to sync up on this.

**Comment by potatodepaulo** [comment]
Keys are stored in home dir until we have more robust and secure key management.

**Comment by janedegtiareva** [comment]
Paper trail: this was fixed in https://github.com/near/near-shell/pull/339
