### ISSUE TITLE
Workshops

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#124]
- [ ] Open Web Workshop @evgenykuzyakov 

@amgando lead on workshops.

**Comment by AnaisUrlichs** [comment]
Just some persona to keep in mind during developing the workshops: [https://github.com/nearprotocol/near-events/issues/22](https://github.com/nearprotocol/near-events/issues/22) + how the workshops connect to communities that we are already working with and the way workshops can be used for them.

**Comment by potatodepaulo** [comment]
Testing needed to ship:
* Three people going through each workshop with a thumbs up or down. owned by @AnaisUrlichs
