### ISSUE TITLE
Fix awesome-near Gatsby setup

### ISSUE THREAD

**Issue by mikedotexe** [near/devx#141]
When trying to restart Gatsby for examples on render.com (look for examples) it fails.
Getting a 401 for GraphQL

https://dashboard.render.com/static/srv-bppa8hbeej5u1763656g/deploys/dep-bqjr2488atna0n3hcaf0

It can run be run locally. since it's a 401 issue, I suspect it may have something to do with the secret instructions to have a Github access token in order to use the GraphQL.

Acceptance criteria: we can go to render.com, log in with our NEAR gmail, and rebuild the site.

**Comment by chadoh** [comment]
Thanks for catching this; I replaced the `GITHUB_TOKEN` with a newly-generated one with the same exact permissions and it has worked twice in a row now. I'm not sure why I've had to do this twice in the last two weeks!
