### ISSUE TITLE
Update Cargo.toml for Rust Status Message example

### ISSUE THREAD

**Issue by mikedotexe** [near/devx#145]
https://github.com/near-examples/rust-status-message/blob/master/Cargo.toml
This is old. It should match:
https://github.com/near/near-sdk-rs/blob/master/examples/status-message/Cargo.toml

Notice serde_json and near-sdk instead of near-bindgen
Run tests and compile according to instructions and make sure nothing breaks. Look at the code in the second link, but in the file `src/lib.rs` and make sure everything looks right.
For instance, this one has `payable` add that if we should add that.
https://github.com/near/near-sdk-rs/blob/master/examples/status-message/src/lib.rs

**Comment by chadoh** [comment]
@evgenykuzyakov why do we have `#[payable]` here? https://github.com/near/near-sdk-rs/blob/master/examples/status-message/src/lib.rs

(Same question asked here: https://github.com/near/near-sdk-rs/pull/137/files#r410946509)
