### ISSUE TITLE
Proof of Work faucet example

### ISSUE THREAD

**Issue by mikedotexe** [near/devx#147]
- [ ] Fix readme to give proper instructions on how to test (in the subdirectory)
- [ ] Add as much to the readme as possible so developers understand how to use this example and what's going on. Including add comments.
- [ ] Frontend folder has a readme about react, I don't think it works. Does it work? No? Remove/modify.
- [ ] Add information about what gh-pages does.

**Comment by chadoh** [comment]
> We want to fix this: https://github.com/near-examples/token-printer/blob/master/contract-rs/src/types.rs
> The U128 shouldn't be a struct, it's in the latest version. See: https://github.com/near/near-sdk-rs/blob/master/examples/fungible-token/src/lib.rs#L16

@mikedotexe this issue is for the Proof of Work faucet, which [doesn't use U128](https://github.com/near-examples/pow-faucet/blob/master/contract-rs/src/lib.rs). Can we remove this requirement?

**Comment by chadoh** [comment]
@mikedotexe I improved the README on the `pow-faucet` example, on which the `token-printer` example is based. I then realized that we were showing the `token-printer` example on examples.near.org and not `pow-faucet`.

I've changed this. You can see my new description at https://examples.near.org/pow-faucet, and at the bottom it links to the `token-printer` GitHub repo.

I think this should be fine, but I wanted to call it out in case there's a good reason to give more prominent display to `token-printer` instead.
