### ISSUE TITLE
Sweep repos and add license info to package.json

### ISSUE THREAD

**Issue by mikedotexe** [near/devx#155]
We don't have a `license` key in many of the package.json files.
We can use:
`{ "license": "(MIT AND Apache-2.0)" }`
just need to make sure we can use AND

Shown here:
https://docs.npmjs.com/files/package.json
`{ "license": "(MIT OR Apache-2.0)" }`

**Comment by potatodepaulo** [comment]
Acceptance Criteria: Add to the following. (In the case of Rust, use Rust's convention)
* near-shell
* near-sdk-as
* near-api-js
* near-sdk-rs

**Comment by potatodepaulo** [comment]
@chadoh is this in progress or done? I saw one PR merged. Does this need more?

**Comment by chadoh** [comment]
I don't think this is done, actually! Sorry, lost track of this; if we still care to do this in one sweep rather than as-we-come-across-them, then I don't think it will take long.

**Comment by chadoh** [comment]
all near-examples repos have been updated, as have near-api-js, create-near-app, near-sdk-as, and near-shell
