### ISSUE TITLE
Sweep examples and fix any usages of near view … --accountId

### ISSUE THREAD

**Issue by mikedotexe** [near/devx#156]
`view` commands do nothing with the flag `--accountId` and we should not provide instructions to add this flag. Sweep through examples and fix this. I think the Rust examples have this, and perhaps others.

**Comment by janedegtiareva** [comment]
PRs in near-examples
https://github.com/near-examples/workshop--exploring-near-apis/pull/2
https://github.com/near-examples/rust-status-message/pull/20

**Comment by chadoh** [comment]
just a note: I mentioned this issue from the two others so that here in this one GitHub shows not just the link, but the current status (both now merged)

were those the only two repos where we did this? if so, this can be closed
