### ISSUE TITLE
Examples: update Cargo.toml for near-sdk

### ISSUE THREAD

**Issue by mikedotexe** [near/devx#157]
Currently Rust examples have:
near-sdk = "0.6.0"
but need to be updated to:
near-sdk = "0.9.2"

Nothing should break. Ensure nothing breaks, please.

**Comment by willemneal** [comment]
Does dependabot work on those examples too?

**Comment by chadoh** [comment]
@willemneal no, dependabot doesn't seem to be checking our Rust deps – not sure why, as that's [purportedly supported](https://dependabot.com/rust/)
