### ISSUE TITLE
Process for responding DevX questions

### ISSUE THREAD

**Issue by ilblackdragon** [near/devx#171]
Do we create issues every time we get a question like this https://near-protocol.slack.com/archives/C01346BPS5T/p1589656379104800 ?
E.g. there are 3 issues here:
 - AS sdk doesn’t have a high level API for funds transfer
 - We don’t have an example of AS contract transferring NEAR :face_palm:
 - We don’t have documentation for transferring NEAR (in both AS and RS)

But more specifically, it’s the process of capturing these -> e.g. ideally the discussion above should be concluded with 3 issues linked. Where 3rd issue should contain response to developer (e.g. like this - https://github.com/nearprotocol/docs/issues/341)

**Comment by potatodepaulo** [comment]
Note: @amgando and I had a 1-1 discussion that covered this in part. Current iteration will likely involve a bot that can port a message body to an issue in the docs.

**Comment by ilblackdragon** [comment]
I don't think it's about bot - I think it's about us following process.
Also SO should be involved as well.

**Comment by potatodepaulo** [comment]
@ilblackdragon I agree. In this case, I view the bot as a way to make process really easy, and few steps to follow.
