### ISSUE TITLE
FT Example: Rust example

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#179]
This might be done. Needs surfacing and a public link + spot checking.

**Comment by janedegtiareva** [comment]
near/initial-contracts has a PR from Willem 
near-sdk-rs has an example 

Acceptance criteria: 

-  minimal version of contract
-  no UI is needed
-  tests
-  final location of the example: near-examples

 
Clarification: what do we want to do with the near/initial-contracts version of the code? 
- duplication to start is okay for now. Will clean up later.

**Comment by potatodepaulo** [comment]
@willemneal will mindfully copy and paste.
