### ISSUE TITLE
FT Example: AssemblyScript implementation

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#180]
Needs updating to follow spec. https://github.com/nearprotocol/NEPs/pull/21.

**Comment by janedegtiareva** [comment]
- There is an existing example on ERC20 (ERC20 in near-examples. Has unit tests but it doesn't have simulation tests)
- Can leverage work from NFT in assembly script
- the simulation tests that are being added to rust cannot be used for assembly script

Acceptance criteria: 

- implement NEP21
- put into near-examples
- unit tests 
- simulation tests (use the jest tests in existing examples)

**Comment by potatodepaulo** [comment]
Needs discussion on whether or not we show this to people: https://github.com/orgs/near/teams/devx/discussions/1
