### ISSUE TITLE
Track Network & OS for Mixpanel

### ISSUE THREAD

**Issue by ashleynear** [near/devx#192]
As a product manager on the DevEx team at NEAR,
I want to know which network the user is on when they are using shell when looking at Mixpanel,
So that I can identify when and if problems are happening on a particular network.

As a product manager on the DevEx team at NEAR,
I want to know which operating system the user is using, 
So that I can flag issues and identify error trends for the development team at NEAR.

**Comment by ashleynear** [comment]
Engineering work (networks): 
- pass on consolidating NodeURL network, Node

Engineering work (OS):
- Use process.platform as an attribute

**Comment by janedegtiareva** [comment]
Let's also add shell version as part of this effort.

**Comment by janedegtiareva** [comment]
We need to log data on both the networkId and nodeUrl, since both pieces of data can be overridden by a developer.
