### ISSUE TITLE
Add Mixpanel tracking for Gitpod instances

### ISSUE THREAD

**Issue by ashleynear** [near/devx#194]
As a product manager on the DevEx team at NEAR,
I want to know when a user goes through different GitPod instances, 
So that I can see the entire user journey. 

As a product manager on the DevEx team at NEAR,
I want to know which platform events are happening on when looking at Mixpanel, which is either:
- Gitpod 
- Local
So that I can look at our data to pinpoint issues with full clarity of where the issue is occurring.

**Comment by ashleynear** [comment]
Engineering work GitPod Instances:
 - Gitpod gives us the following
`Env in gitpod includes GITPOD_GIT_USER_NAME=Sherif Abushadi GITPOD_GIT_USER_EMAIL=sherif@amgando.org` <- we cannot log PII at least, not in this form.
- So then hash it. 
- Add to Mixpanel


Engineering work for separating between Gitpod & Local:
- use this [link with information](https://github.com/near/near-shell/pull/376/files#diff-22c1137743448ab1baa32f6696424c4fR13)

**Comment by janedegtiareva** [comment]
Clarifying q: when we log a hash of user id in gitpod, do we want to replace the existing distinct id, or add a new data field? This has impact on how users will be grouped in mixpanel UI.
