### ISSUE TITLE
Consent for tracking on NEAR.org/ Gitpod

### ISSUE THREAD

**Issue by ashleynear** [near/devx#198]
As a developer on the NEAR platform,
I want to be informed, aware, and have the option to refuse or consent to my data being monitored anytime I interact with:

- Shell
- Wallet
- Gitpod (IDE)
- The website

So that I have the ability to make an informed decision on if I want to give my data to NEAR.

**Comment by chadoh** [comment]
@vgrichina [recently removed](https://github.com/near/near-shell/commit/f46416667d17454fc9808e7e3ca760c4bd96c2fb) the near-shell tracking opt-in on Gitpod, since there was no way to prevent it from opening every time you restart a workspace, which happens all the time in a Gitpod workflow. Additionally, if you're using a web-based IDE, you probably expect everything you do to be tracked already. 

I'm curious where this new requirement is coming from, and how we plan to fix the usability issues that we ran into last time.

**Comment by ashleynear** [comment]
Engineering Time:
- Try to figure out how we can not re-prompt the same user over & over [see helpful docs](https://www.gitpod.io/docs/config-start-tasks)
- if possible, implement that as part of doing the consent to opt-in

Back up:
- Prompt in the readme.Gitpod file
- Linking to the examples of how we are using this data


 [Discussion](https://github.com/orgs/near/teams/devx/discussions/2)

**Comment by ashleynear** [comment]
Cross posting this to NEAR/NEAR-wallet on Github cc: @kcole16

**Comment by janedegtiareva** [comment]
I spent about 1/2 hour looking through the docs linked above, and haven't seen anything that would let us save the opt-in/out info between gitpod sessions. Do we want to spend more time on this, or go with the fallback?

**Comment by ashleynear** [comment]
@janedegtiareva Let's go with the fallback -- any protest @potatodepaulo ?

**Comment by janedegtiareva** [comment]
We need text to put into the README.

**Comment by mikedotexe** [comment]
"By using Gitpod in this project, you agree to opt-in to basic, anonymous analytics. No personal information is transmitted. Instead, these usage statistics aid in discovering potential bugs and user flow information."

I think we can add this to `near-shell` and all the examples at https://near.dev
For the repos with a `README-Gitpod.md` file, it can go in there. For those that don't have it, the regular `README.md` file will do

**Comment by janedegtiareva** [comment]
> "By using Gitpod in this project, you agree to opt-in to basic, anonymous analytics. No personal information is transmitted. Instead, these usage statistics aid in discovering potential bugs and user flow information."
> 
> I think we can add this to `near-shell` and all the examples at https://near.dev
> For the repos with a `README-Gitpod.md` file, it can go in there. For those that don't have it, the regular `README.md` file will do

Thank you! I can put this into readmes.
