### ISSUE TITLE
Fix the create-near-app build

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#199]

**Comment by janedegtiareva** [comment]
just make the build green

**Comment by janedegtiareva** [comment]
This is an as-pect error (dependency of near-sdk-as). Once the updated versions are published, we need to bump the dependency to fix builds.

**Comment by janedegtiareva** [comment]
Fixed here by bumping near-sdk-as https://github.com/near/create-near-app/pull/337
near-sdk-as fix here https://github.com/near/near-sdk-as/pull/104/files
