### ISSUE TITLE
Implement crash reporting in Mixpanel

### ISSUE THREAD

**Issue by ashleynear** [near/devx#202]
As a pm at NEAR,
I want the ability to have crash reporting on Mixpanel, 
So that I can identify when crashes are happening and why. 

As a PM at NEAR,
I want the _start_ and _end_ to be removed from Mixpanel,
so that the crashes are clearly identified without additional steps.

*Keep the log at the beginning of a call not the end

**Comment by ashleynear** [comment]
Engineering  work:
- find a way to track what happened
[Context](https://github.com/near/near-shell/tree/hotfix/mixpanel-crash-reporting)
- plug it into the shell & mixpanel backend
- test to see that crashes are recorded

**Comment by janedegtiareva** [comment]
https://github.com/near/near-shell/pull/401

**Comment by janedegtiareva** [comment]
Note on PII: logging full data from crash reports will result in us having some pii (e.g. account id that was looked up and was not found). Filtering PII out from error details is out of scope right now.

**Comment by potatodepaulo** [comment]
Is it possible to do a pared down version of the report? E.g. just the fact that it crashed to start?
