### ISSUE TITLE
inconsistent case in shell commands and flags

### ISSUE THREAD

**Issue by Sladuca** [near/devx#203]
Describe the bug
The shell is inconsistent in how it names flags and commands, and it would be much better DevX if they were consistent. 

To Reproduce

run `near help` and look at the variety of case usage in the commands and flags.

Version (please complete the following information):

near shell 0.23.2
testnet

Additional context

For example, `create_account`, `tx-status`, `--masterAccount` all use different case. I'd be happy to self-assign this issue if y'all are working on better things.

Still by far the best DevX I've had for blockchain development, and I can't wait for it to get better :)

**Comment by janedegtiareva** [comment]
AC: 
* establish naming convention for shell commands
* update shell interface to use the new naming convention
* make sure the old version of commands still work for backwards compatibility
* update docs throughout to use new versions of commands, or file issues in relevant repos.

**Comment by mikedotexe** [comment]
I think we can avoid fallout by:
rename create_account to create-account, for instance
create a new command called create_account that spits out a message saying, "this is deprecated, friend" and is hidden, but then calls create-account

**Comment by Sladuca** [comment]
In addition, I think the message should say something like "we've switched all commands to dash-case" so that's not super confusing.

**Comment by janedegtiareva** [comment]
> I think we can avoid fallout by:
> rename create_account to create-account, for instance
> create a new command called create_account that spits out a message saying, "this is deprecated, friend" and is [hidden](https://yargs.js.org/docs/#api-optionskey-opt), but then calls create-account

Quick aside: yargs hidden feature only applies to options, but apparently commands don't show up in help if you leave the description blank.

**Comment by janedegtiareva** [comment]
Here is a problematic case which makes handling of the options a more complex undertaking: 
https://github.com/near/near-shell/pull/414

If we change all options to be dash-case canonically, there may be more regressions like this. Making this change would require a thorough re-test of all the commands.

**Comment by mikedotexe** [comment]
Is this still "in progress"?
