### ISSUE TITLE
Change all the rust examples and create-near-app to work with changes to sdk

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#209]
Context: https://github.com/near/near-sdk-rs/releases/tag/v0.11.0

Acceptance criteria:
* When the repos are updated with the latest near-sdk-rs it will all break. They shouldn't break.

**Comment by janedegtiareva** [comment]
There are a lot of rust examples which are not supported. Is the plan to leave them with the old version?

**Comment by janedegtiareva** [comment]
We don't have dependabot set up for all examples right now, so this issue just picked up scope (configure dependabot for all examples that we support)
