### ISSUE TITLE
 NEAR Homepage Context

### ISSUE THREAD

**Issue by ashleynear** [near/devx#211]
As a developer using the NEAR create-near-app,
I want clear context and information for what I am doing on the homepage: 

- Explain what the command is going to do, and what the expected result will be.
- Provide the exact prerequisites & installs I will need
- Provide the versions of each install that I will need

So that I know what I am doing and am prepared to do it.

**Comment by janedegtiareva** [comment]
The installation instructions on nodejs.org do not work with create-near-app for a fresh mac. We need to increase the scope and add a doc page with recommended node installation steps.

**Comment by janedegtiareva** [comment]
Proposed text: 
Deploy your first app with NEAR in under 5 minutes. Make sure you have [Node.js] (should link to https://nodejs.org/en/download/package-manager/), then run this command to initialize a web app. It will walk you through from there!

**Comment by ashleynear** [comment]
@janedegtiareva whats the status here?

**Comment by janedegtiareva** [comment]
The update has been applied to near.org. We can close this.
