### ISSUE TITLE
NEAR shell Context

### ISSUE THREAD

**Issue by ashleynear** [near/devx#212]
As a developer using the NEAR create-near-app,
I want clear context and information for what I am doing in the NEAR shell,

- Explain what this app is supposed to do
- Explain the links that pop up and what they do (or make them load when you click them) (Or hide them)
- I.e. helper.testnet.near

So that I know what I am doing.

**Comment by janedegtiareva** [comment]
Clarifying screenshot:

![Screen Shot 2020-06-29 at 4.59.37 PM.png](https://images.zenhubusercontent.com/5cf050b76757146a9c288c1e/883293ac-7fea-4b61-8b34-09b81126598e)

To remove the "using option" section, we need to add a quiet mode in shell which hides the extra output.

**Comment by janedegtiareva** [comment]
https://github.com/near/near-shell/pull/440

**Comment by janedegtiareva** [comment]
The first part of the task is complete (hiding connection options). 

re clickable link copying slack conversation for context
This is output that a third party npm package produces, so we can't control if it's clickable or not. 
@vgrichina suggested to use the -o option that opens the browser automatically. After about 1 hr of trying it: it does not integrate easily into the way the packages are stitched together in our scripts. 
@mikedotexe  suggested, You can hit Command has you hover over the link to make it clickable, possibly Control in Windows. I tried this, and it does not work on Windows.

**Comment by mikedotexe** [comment]
@janedegtiareva I used the `--help` command on parcel to see what options are available. `--open` seems to do what we want
![2020-07-07 17_35_47-Window](https://user-images.githubusercontent.com/1042667/86859919-a7ad9180-c078-11ea-921c-d9921cfc2a46.png)

**Comment by janedegtiareva** [comment]
Estimation calibration: this turned out to be a heavy 5 due to changes in multiple projects and the need to test on different platforms due to  non-trivial package.json changes.
