### ISSUE TITLE
 create-near-app README Context

### ISSUE THREAD

**Issue by ashleynear** [near/devx#213]
As a developer using the NEAR create-near-app,
I want clear context and information for what I am doing in the README:

- Explain what NEAR Shell is
- Explain what testnet is
- Explain what the app is supposed to do
- Explain what the expected results will be
- Explain what devnet is	

So that I know what I am doing.

**Comment by ashleynear** [comment]
NOTES: Consider updating title of README to Hello World on NEAR

**Comment by ashleynear** [comment]
@chadoh who are you waiting on for a review for this bad boy?

**Comment by chadoh** [comment]
@mikedotexe or @janedegtiareva, as noted in the linked PR
