### ISSUE TITLE
Easy to follow Calls to Action

### ISSUE THREAD

**Issue by ashleynear** [near/devx#218]
As a developer using the NEAR create-near-app,
I want the instructions and call to actions in the NEAR shell to be clear and easy to follow such as:

- The call to action to click the localhost:1234 link
- The calls to action to type in cd-your-awesome-project & yarn dev

So that I don’t get lost and stop trying.

**Comment by chadoh** [comment]
This is what you see right now when you first create a new project:

![we suggest you begin by typing cd lol && yarn dev](https://user-images.githubusercontent.com/221614/86422725-e673ce00-bcab-11ea-9fad-590516cf9f5d.png)

and this is what you see when you type `yarn dev`:

![image](https://user-images.githubusercontent.com/221614/86422772-10c58b80-bcac-11ea-8b5e-a4bacf6aac00.png)

Most web developers will know what this means immediately. For those who don't we have this line in the README added in near/create-near-app#389:

> Running `yarn dev` will tell you the URL you can visit in your browser to see the app.

I think this all seems sufficient. The only improvement I would suggest at this time is auto-opening the browser to `localhost:1234`.

What do you think, @ashleynear?

**Comment by ashleynear** [comment]
I love the idea of an auto-opened browser personally. Let's do it! @chadoh

**Comment by ashleynear** [comment]
@chadoh I don't see you assigned to this issue but thought you were...did you want to take it?

**Comment by chadoh** [comment]
Happy to, @ashleynear

**Comment by ashleynear** [comment]
@chadoh heyo, whats the status on this?

**Comment by chadoh** [comment]
This was fixed by https://github.com/near/create-near-app/pull/399 – thanks, @janedegtiareva!
