### ISSUE TITLE
Chainlink - provide JSON structure for get_requests_summary and get_request

### ISSUE THREAD

**Issue by mikedotexe** [near/devx#224]
Chainlink is blocked, probably because of timeout issues on testnet, in following the README to get the structure of the requests in the oracle contract state.

![Screenshot 2020-07-07 13.39.07.png](https://images.zenhubusercontent.com/5a60db2a4b5806bc2bc34af6/6ead3642-6248-4ad6-a2d8-478049ae6af8)

In order to unblock, we need to provide him with mock requests and what the JSON looks like so he can continue work on the external initiator.

**Comment by bowenwang1996** [comment]
@potatodepaulo @mikedotexe can you provide more context?

**Comment by mikedotexe** [comment]
> @potatodepaulo @mikedotexe can you provide more context?

Sure, so it's a fairly simple task. I have created a pretty in-depth README for the version 1 of the oracle that includes scripts to deploy various contracts to subaccounts, make a request, and then query for requests as if you're an oracle node. Kristijan, the developer at Chainlink was unable to follow these instructions because of incessant timeouts today. So I'm going to try running a node locally and giving him the structure of the JSON that gets returned so he can be unblocked.

**Comment by bowenwang1996** [comment]
@mikedotexe do you need anything from me? Also the issue on testnet should resolve in at most 8 hours.

**Comment by mikedotexe** [comment]
> @mikedotexe do you need anything from me? Also the issue on testnet should resolve in at most 8 hours.

Thanks for checking in, Bowen. I'm good. I'm going to wrap up other tasks that don't need testnet and then get back to it later tonight.
