### ISSUE TITLE
near-shell 1.0.0 release

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#237]
We need to release a cut of the cli tool that we can tell people they can rely on.

**Comment by janedegtiareva** [comment]
Do we want to agree on a release process? e.g. start QAing before publish, etc

**Comment by janedegtiareva** [comment]
Another consideration: do we want to publish near-api-js 1.0.0 before we publish near-shell 1.0.0? We do not want to have an unstable major dependency for a package we are claiming to be stable

**Comment by janedegtiareva** [comment]
We can easily change to near-cli if we have 2 libraries for a time (both near-cli and near-shell). near-shell will re-export near-cli

**Comment by mikedotexe** [comment]
Not going to be done by the end of the month, tomorrow, but will do next week.
