### ISSUE TITLE
Sweep code/deployed sites/docs and remove devnet

### ISSUE THREAD

**Issue by janedegtiareva** [near/devx#244]
Devnet was deprecated, so we need to remove mentions of it.

**Comment by thisisjoshford** [comment]
working on the `docs` portion of this issue now... : )

**Comment by thisisjoshford** [comment]
`docs` portion of this issue is complete with [PR #420](https://github.com/near/docs/pull/420) awaiting review : )

**Comment by janedegtiareva** [comment]
All references have been dealt with (either removed or issues filed in specific repos)
