### ISSUE TITLE
dev-deploy is failing if explorerUrl is in config.js

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#247]
When you generate a new project, `yarn dev` will not run.
For an existing project dev-deploy will not run.

Repro:
1. Run `near-dev` in a project after upgrading near-shell. 
2. See `Unknown argument: explorerUrl` or ` Exceeded 10 status check attempts for transaction`

**Comment by janedegtiareva** [comment]
@potatodepaulo could you upgrade to latest shell? This will make the error go away. 
We should to upgrade shell dependency to latest in create-near-app and publish

**Comment by potatodepaulo** [comment]
This is repro for clean install of 0.24.9 (currently latest)

**Comment by chadoh** [comment]
Fixed with [create-near-app@1.1.6](https://github.com/near/create-near-app/releases/tag/v1.1.6)
