### ISSUE TITLE
Example: key-value store for easy interactions

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#248]
v1: Store data in the simplest way possible
v2: Allow devs to be more specific - E.g. storing their users data against account ids

**Comment by mikedotexe** [comment]
@thisisjoshford can we move this to In Review? not sure of the status on it, but I think you're finished

**Comment by thisisjoshford** [comment]
v1 is complete @mikedotexe. v2 & v3 will be completed after first publishing v1 example, so maybe this issue should stay active?

**Comment by behaviary** [comment]
Sorry this was blocked. We can split out into multiple issues

**Comment by behaviary** [comment]
Okay, whittled this down and created a separate issues so we can better parallelize. https://github.com/near/devx/issues/258
