### ISSUE TITLE
Build Examples and Templates

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#25]
As per suggestion from @kcole16, examples and templates should be prioritized based on what features we want to showcase and demonstrate.

**Comment by vgrichina** [comment]
I think our examples should cover stuff that we want to demonstrate, but also be prioritized based on fun factor. If example isn't fun – it won't get much attention either internally or externally. E.g. crypto corgis are fun (at least if well implemented) and actually can even help push our wallet forward (as we don't have support for custom tokens yet).

**Comment by kcole16** [comment]
Agree with @vgrichina re: fun factor! Ideally demonstrating some of the following (not comprehensive) while showcasing an exciting and good use of a blockchain.

- Contracts in Rust and AssemblyScript
- Cross-contract calls
- Creating batch transactions in a function ([example](https://github.com/nearprotocol/near-bindgen/blob/master/examples/cross-contract-high-level/src/lib.rs#L45))
- Using tokens
    - [Fungible](https://github.com/nearprotocol/near-bindgen/tree/master/examples/fun-token)
    - [Non-fungible](https://github.com/nearprotocol/corgis)
    - Safes (DEXs, swaps, etc)
- Application level patterns
    - Login w/ NEAR
    - On-demand TX signing
    - Deploying contracts to user accounts

**Comment by potatodepaulo** [comment]
Note: We will be hosting examples [here](https://github.com/near-examples) moving forward. This is to automate the example index. 
* [ ] Add tags to repos to allow users to sort and find by use case.
