### ISSUE TITLE
Fix awesome-near examples

### ISSUE THREAD

**Issue by mikedotexe** [near/devx#38]
Examples should run in Gitpod and locally when cloned
See Kendall's Gitpod transition plan:
https://docs.google.com/document/d/1Ri0pYN7c7eScdcSmcbgjVK1HvR8gGEH_80Ac3iAmEhM/edit#

And the repo:
https://github.com/nearprotocol/awesome-near

**Comment by amgando** [comment]
this work is likely related to Epic https://github.com/near/devx/issues/43

- [ ] all the examples run in gitpod and locally

**Comment by mikedotexe** [comment]
Closing as each example should/will have its own ticket. Relevant info from this ticket moved to comments in the epic.
