### ISSUE TITLE
[Docs] Clear out the near studio related content from docs and readmes

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#44]

**Comment by amgando** [comment]
possible work items related to Epic https://github.com/near/devx/issues/43

- [ ] documentation doesn't have links to studio
- [ ] all the READMEs are updated

**Comment by potatodepaulo** [comment]
Note: Please update READMEs with perspective that new dev doesn't know what's going on.

**Comment by potatodepaulo** [comment]
Note from discussion: Add notes to all pages that are out of date because of Studio removal as a stop gap until we have a chance to update them to use gitpod.

**Comment by amgando** [comment]
couple options for the note styling for temp docs update.  any preference?

# choose 🚀for this style
![image](https://user-images.githubusercontent.com/24913/77468174-4f7eb680-6e1e-11ea-8df6-dc6b564c1f56.png)

# choose 🎉for this style
![image](https://user-images.githubusercontent.com/24913/77468201-54436a80-6e1e-11ea-8643-5ca5006307aa.png)

**Comment by AnaisUrlichs** [comment]
I am aware that I am quite late to this; the docs seems updated for the most part in callouts and most links to studio removed (besides those that link to the tutorials). See [branch](https://github.com/nearprotocol/docs/tree/remove-studio-2)
Added some minor changes in new branch (tb pushed).

What is left:
* The website has two major links showcasing studio
    [https://nearprotocol.com/get-started/](https://nearprotocol.com/get-started/)
    [https://nearprotocol.com/developers/](https://nearprotocol.com/developers/)
