### ISSUE TITLE
[Tracking issue] Update the examples following the renamings of near-* packages

### ISSUE THREAD

**Issue by frol** [near/devx#89]
* `nearlib` was renamed to [`near-api-js`](https://github.com/near/near-api-js) (/cc @vgrichina)

  * the repository name is `near-api-js`
  * the NPM package and the import names *are going to be* `near-api-js`
* `near-bindgen-as` (previously also known as `near-runtime-ts`) was renamed to [`near-sdk-as`](https://github.com/near/near-sdk-as) (/cc @willemneal)

  * the repository name is `near-sdk-as`
  * the NPM package and the import names are `near-sdk-as`
* `near-bindgen` was renamed to [`near-sdk-rs`](https://github.com/near/near-sdk-rs) (https://github.com/near/near-sdk-rs/pull/114, https://github.com/near/near-sdk-rs/pull/112) (/cc @nearmax)

  * the repository name is `near-sdk-rs`
  * the package name is `near-sdk` (dependency in Cargo.toml)
  * the use statement should be updated to `use near_sdk::near_bindgen;`

The packages with the old names are still available on the package repositories, but they won't get new updates, so we should follow the renaming and update our examples and documentation sooner rather later.

I assign this issue to @potatodepaulo to schedule this work for the DevX team.

**Comment by nearmax** [comment]
Thank you for keeping an eye on it, @frol !

**Comment by ilblackdragon** [comment]
Also documentation really needs to be updated @amgando :
 - https://docs.nearprotocol.com/docs/roles/developer/examples/nearlib/introduction
 - https://docs.nearprotocol.com/docs/near-bindgen/near-bindgen
 - https://docs.nearprotocol.com/docs/roles/developer/contracts/assemblyscript
etc

**Comment by willemneal** [comment]
Also `near-runtime-ts` -> `near-sdk-as`
